### PR TITLE
Deadlock bug fix v4

### PR DESCRIPTION
**Pull request by vmx**
A new day a new PR.

We are getting closing fixing all deadlocks and race conditions. This PR take the code from the the previous attempts at #147, #148, #149 and re-arranges them into known good ones and bad ones. The first few commits are known to be good and pass CI (at least the tests, the coverage fails, that's something to look into next). Those are the commits up to (including) https://github.com/filecoin-project/bellperson/commit/e6f32da78f22b308f72589b2a8a5ff3cfb5094c8

Though there is still a potential deadlock left in the GPU code path. The newer commits try to fix that one, but doesn't succeed as can be seen on the failing CI.

### CODE REVIEW

**Comment by vmx** [comment]
To the one who merges this PR, please do a me a favour and do a "Rebae and merge" merge :)

**Comment by cryptonemo** [comment]
@dignifiedquire We are looking to release this as a patch release today.  At some point after, another patch release with some cleanups and re-factors by @vmx will likely happen on the sooner side.

**Comment by cryptonemo** [comment]
@vmx -- I just rebased this against the latest since a release happened yesterday.  If you want to put the commit history back to how you had it (and re-do the rebase), feel free.

**Comment by cryptonemo** [comment]
@vmx Actually, I'm going to back this out myself and use the 'rebase and merge' as you suggested.  Sorry, I missed that.

**Review by dignifiedquire — APPROVED** [review]

**Pull request merged**
